// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFyLMM9jF_jQHd6DzM-zhLShMHFW-rUbY',
    appId: '1:998135056333:web:95d6590ca24d802f41a684',
    messagingSenderId: '998135056333',
    projectId: 'libpulse-89590',
    authDomain: 'libpulse-89590.firebaseapp.com',
    storageBucket: 'libpulse-89590.firebasestorage.app',
    measurementId: 'G-9TBFSY6J0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMDkYaece2Nj7eibmC-4ivl1Q-vSWjr7M',
    appId: '1:998135056333:android:40d7dc74d120c69441a684',
    messagingSenderId: '998135056333',
    projectId: 'libpulse-89590',
    storageBucket: 'libpulse-89590.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXzi8Q8J5XrZK1441YQNzQb6m2rru5sG4',
    appId: '1:998135056333:ios:4aac6c3548d2ca8141a684',
    messagingSenderId: '998135056333',
    projectId: 'libpulse-89590',
    storageBucket: 'libpulse-89590.firebasestorage.app',
    iosBundleId: 'com.example.libPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXzi8Q8J5XrZK1441YQNzQb6m2rru5sG4',
    appId: '1:998135056333:ios:4aac6c3548d2ca8141a684',
    messagingSenderId: '998135056333',
    projectId: 'libpulse-89590',
    storageBucket: 'libpulse-89590.firebasestorage.app',
    iosBundleId: 'com.example.libPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFyLMM9jF_jQHd6DzM-zhLShMHFW-rUbY',
    appId: '1:998135056333:web:76c2c8267b97ca9c41a684',
    messagingSenderId: '998135056333',
    projectId: 'libpulse-89590',
    authDomain: 'libpulse-89590.firebaseapp.com',
    storageBucket: 'libpulse-89590.firebasestorage.app',
    measurementId: 'G-RHN9V42TW9',
  );

}